name: fashion_store
description: "A complete Flutter fashion e-commerce app with Firebase backend"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # UI Components
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.2.0+3
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
