// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3B4b-PCI-SLgQqla1u9WqMKvPKIrWwJA',
    appId: '1:956381018961:web:c9d8c3bb633b2180377170',
    messagingSenderId: '956381018961',
    projectId: 'fashion-store-app-91194',
    authDomain: 'fashion-store-app-91194.firebaseapp.com',
    storageBucket: 'fashion-store-app-91194.firebasestorage.app',
    measurementId: 'G-PFQ81G4GLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArBXtEw5xUTpbc_s5PLNS7o0Jlfc3JomU',
    appId: '1:956381018961:android:e01eec47fdfb7dfc377170',
    messagingSenderId: '956381018961',
    projectId: 'fashion-store-app-91194',
    storageBucket: 'fashion-store-app-91194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ_i9-QfICzM4C-3ivpcgayKpCQQ8soXo',
    appId: '1:956381018961:ios:e9d861c2386267d3377170',
    messagingSenderId: '956381018961',
    projectId: 'fashion-store-app-91194',
    storageBucket: 'fashion-store-app-91194.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ_i9-QfICzM4C-3ivpcgayKpCQQ8soXo',
    appId: '1:956381018961:ios:e9d861c2386267d3377170',
    messagingSenderId: '956381018961',
    projectId: 'fashion-store-app-91194',
    storageBucket: 'fashion-store-app-91194.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3B4b-PCI-SLgQqla1u9WqMKvPKIrWwJA',
    appId: '1:956381018961:web:16c7d1250308dfa6377170',
    messagingSenderId: '956381018961',
    projectId: 'fashion-store-app-91194',
    authDomain: 'fashion-store-app-91194.firebaseapp.com',
    storageBucket: 'fashion-store-app-91194.firebasestorage.app',
    measurementId: 'G-JTD10TB33D',
  );

}